// Sound-effect playback for the synthesized WAVs in /assets/sounds
// (generated by scripts/sounds.ts). Presentational only: playing a sound
// never touches game state. Callers gate on the Sound setting themselves
// via the `enabled` argument so this module stays store-free.

import {
  createAudioPlayer,
  setAudioModeAsync,
  type AudioPlayer,
  type AudioSource,
} from 'expo-audio';

const SOURCES = {
  crunch: require('../../assets/sounds/crunch.wav') as AudioSource,
  yelp: require('../../assets/sounds/yelp.wav') as AudioSource,
  crack: require('../../assets/sounds/crack.wav') as AudioSource,
  bark: require('../../assets/sounds/bark.wav') as AudioSource,
  land: require('../../assets/sounds/land.wav') as AudioSource,
  door: require('../../assets/sounds/door.wav') as AudioSource,
} as const;

export type SfxKey = keyof typeof SOURCES;

const players = new Map<SfxKey, AudioPlayer>();
let loading: Promise<void> | null = null;
let generation = 0;

/** Preload every effect. Safe to call repeatedly; loads once. */
export function initSfx(): Promise<void> {
  if (loading) return loading;
  const gen = generation;
  loading = (async () => {
    await setAudioModeAsync({
      playsInSilentMode: false,
      interruptionMode: 'duckOthers',
      shouldPlayInBackground: false,
    }).catch(() => {});
    for (const key of Object.keys(SOURCES) as SfxKey[]) {
      if (gen !== generation) return;
      try {
        const player = createAudioPlayer(SOURCES[key]);
        // If unloadSfx ran while this was loading, don't leak the player.
        if (gen === generation) players.set(key, player);
        else player.remove();
      } catch {
        // Missing/failed sound is never fatal — the game plays silently.
      }
    }
  })();
  return loading;
}

/** Fire-and-forget playback (restarts the sample if already playing). */
export function playSfx(key: SfxKey, enabled: boolean): void {
  if (!enabled) return;
  const player = players.get(key);
  if (player) {
    player.seekTo(0).catch(() => {});
    player.play();
  } else {
    // Not loaded yet — kick off loading so later plays work.
    void initSfx();
  }
}

/** Release native players (call when leaving the game). */
export async function unloadSfx(): Promise<void> {
  generation += 1;
  const all = [...players.values()];
  players.clear();
  loading = null;
  for (const player of all) {
    try {
      player.remove();
    } catch {
      // ignore
    }
  }
}
