// Sound-effect playback for the synthesized WAVs in /assets/sounds
// (generated by scripts/sounds.ts). Presentational only: playing a sound
// never touches game state. Callers gate on the Sound setting themselves
// via the `enabled` argument so this module stays store-free.

import { Audio, type AVPlaybackSource } from 'expo-av';

const SOURCES = {
  crunch: require('../../assets/sounds/crunch.wav') as AVPlaybackSource,
  yelp: require('../../assets/sounds/yelp.wav') as AVPlaybackSource,
  crack: require('../../assets/sounds/crack.wav') as AVPlaybackSource,
  bark: require('../../assets/sounds/bark.wav') as AVPlaybackSource,
  land: require('../../assets/sounds/land.wav') as AVPlaybackSource,
  door: require('../../assets/sounds/door.wav') as AVPlaybackSource,
} as const;

export type SfxKey = keyof typeof SOURCES;

const sounds = new Map<SfxKey, Audio.Sound>();
let loading: Promise<void> | null = null;
let generation = 0;

/** Preload every effect. Safe to call repeatedly; loads once. */
export function initSfx(): Promise<void> {
  if (loading) return loading;
  const gen = generation;
  loading = (async () => {
    await Audio.setAudioModeAsync({
      playsInSilentModeIOS: false,
      shouldDuckAndroid: true,
      staysActiveInBackground: false,
    }).catch(() => {});
    await Promise.all(
      (Object.keys(SOURCES) as SfxKey[]).map(async (key) => {
        try {
          const { sound } = await Audio.Sound.createAsync(SOURCES[key], { shouldPlay: false });
          // If unloadSfx ran while this was loading, don't leak the player.
          if (gen === generation) sounds.set(key, sound);
          else await sound.unloadAsync().catch(() => {});
        } catch {
          // Missing/failed sound is never fatal — the game plays silently.
        }
      }),
    );
  })();
  return loading;
}

/** Fire-and-forget playback (restarts the sample if already playing). */
export function playSfx(key: SfxKey, enabled: boolean): void {
  if (!enabled) return;
  const sound = sounds.get(key);
  if (sound) {
    sound.replayAsync().catch(() => {});
  } else {
    // Not loaded yet — kick off loading so later plays work.
    void initSfx();
  }
}

/** Release native players (call when leaving the game). */
export async function unloadSfx(): Promise<void> {
  generation += 1;
  const all = [...sounds.values()];
  sounds.clear();
  loading = null;
  await Promise.all(all.map((s) => s.unloadAsync().catch(() => {})));
}
